services:
  event-postgres:
    image: postgres:16
    container_name: eventflow-event-postgres
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: eventflow
      POSTGRES_PASSWORD: eventflow
    ports:
      - "5433:5432"
    volumes:
      - event-postgres-data:/var/lib/postgresql/data

  booking-postgres:
    image: postgres:16
    container_name: eventflow-booking-postgres
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: eventflow
      POSTGRES_PASSWORD: eventflow
    ports:
      - "5434:5432"
    volumes:
      - booking-postgres-data:/var/lib/postgresql/data

volumes:
  event-postgres-data:
  booking-postgres-data: