server:
  port: 8081

spring:
  application:
    name: event-service

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5433/event_db
    username: eventflow
    password: eventflow